services:
  backend:
    build: ./backend
    container_name: web4-backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend/src/data:/app/src/data
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: web4-frontend
    ports:
      - "5500:5500"
    depends_on:
      - backend
    restart: unless-stopped
